### ISSUE TITLE
Problem with `mfo` in Tables/CMIP5_Omon

### ISSUE THREAD

**Issue by ledm** [PCMDI/cmip5-cmor-tables#1]
The `oline` axis in the file `Tables/CMIP5_Omon` needs to be corrected, please. This axis is exclusively used by the `mfo` variable, to describe the name of an ocean passage, such as a Bering straight, or the Drake passage. 

In the `mfo` CMIP5 files on BADC, the `oline` axis name in the file is recorded as `passage`, but the  CMOR table doesn't match as the `out_name` is set to `line`. 

Please change line 187 in the file `Tables/CMIP5_Omon` from:
```
out_name:         line
```
to:
```
out_name:         passage
```

This issue is more fully described the ESMValTOol v2 issue [673](https://github.com/ESMValGroup/ESMValTool/issues/673), and in the pull request [711](https://github.com/ESMValGroup/ESMValTool/pull/711).

Also note that I'm not sure which is incorrect, the CMOR tables or the model data on BADC.

**Comment by doutriaux1** [comment]
@taylor13 are you fine with this change?

**Comment by ledm** [comment]
Hi,

I've found another issue with this file. 

Line 187 is 
```
out_name:         line
```
but it should be:
```
out_name:         passage
```
as `passage` is the term used in all of the CMIP5 observational data.


ie:
```
!============
axis_entry: oline
!============
!----------------------------------
! Axis attributes:
!----------------------------------
standard_name:    region
long_name:        ocean passage 
!----------------------------------
! Additional axis information:
!----------------------------------
out_name:         passage
type:             character
requested:        barents_opening bering_strait canadian_archipelago denmark_strait drake_passage english_channel pacific_equatorial_undercurrent faroe_scotland_channel florida_bahamas_strait fram_strait iceland_faroe_channel indonesian_throughflow mozambique_channel taiwan_luzon_straits windward_passage        ! space-separated list of requested coordinates 
must_have_bounds: no
coords_attrib:    passage
!----------------------------------
!

```

**Comment by durack1** [comment]
@ledm just curious, are you planning to use these tables to write CMIP6 data? If yes, then I recommend you stop. We have a new set of tables and executables (CMOR 3.4.0) for CMIP6, these old CMIP5 tables have been considerably superseded.

**Comment by ledm** [comment]
I'm using these tables as part of ESMValTool. I'm hoping to use ESMValTool to evaluate both CMIP5 and CMIP6 data at the same time.

ESMValTool directly uses these tables to inform the tool how to access and load CMIP5 data. However, the differences between the CMOR tables and the CMIP5 files on ESGF cause the loading to fail.  

For instance, one of the differences is that the CMOR table has a "line" dimension in the mfo field, but the netcdf's on ESGF use the "passage" dimension instead. Perhaps it is the modellers who have all used the wrong term. Nevertheless, they all uniformly have used the "wrong" dimension name, so it's probably easier to change the table after the fact.

**Comment by durack1** [comment]
@ledm if a modeling group has used these tables to generate CMIP5 data (back in ~2012) then their data will have the characteristics contained in these files. I don't think changing these tables to account for data no produced using CMOR is a great idea, as you will find clashes once you start to interrogate files that do have the correct characteristics.

@taylor13 @doutriaux1 any comments here?

**Comment by taylor13** [comment]
At least in one of the CMIP5 files I just downloaded from the CMIP5 archive -- mfo_Omon_CanESM2_historicalGHG_r5i1p1_185001-201212.nc  --  the coordinate information is correct and consistent with the original CMIP5 CMOR tables.  Here is a partial ncdump:
```
dimensions:
	time = UNLIMITED ; // (1956 currently)
	line = 15 ;
	bnds = 2 ;
	strlen = 31 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 1850-1-1" ;
		time:calendar = "365_day" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
	double time_bnds(time, bnds) ;
	char passage(line, strlen) ;
		passage:long_name = "ocean passage" ;
		passage:standard_name = "region" ;
	float mfo(time, line) ;
		mfo:standard_name = "sea_water_transport_across_line" ;
		mfo:long_name = "Sea Water Transport" ;
		mfo:units = "kg s-1" ;
		mfo:original_name = "VMFO" ;
		mfo:cell_methods = "time: mean (interval: 20 minutes)" ;
		mfo:history = "2011-09-29T19:56:47Z altered by CMOR: replaced missing value flag (1e+38) with standard missing value (1e+20)." ;
		mfo:missing_value = 1.e+20f ;
		mfo:_FillValue = 1.e+20f ;
		mfo:associated_files = "baseURL: http://cmip-pcmdi.llnl.gov/CMIP5/dataLocation gridspecFile: gridspec_ocean_fx_CanESM2_historicalGHG_r0i0p0.nc" ;
		mfo:coordinates = "passage" ;
```
So mfo is a function of "line" (not passage), but it has a coordinates attribute that points the user to a variable named "passage" that contains the names of (i.e., labels associated with)( the passages and which itself is a function of "line".

This file is correct and again it is consistent with the CMIP5 CMOR table.  Note that "string" variables like "passage" cannot be used as axes under the CF conventions.

Note also that the CMIP6 CMOR tables define mfo (and its axes and coordinates) consistent with CMIP5 *except* coordinates = "sector" (not "passage"), so the labels for the "line" axis are stored in variables named differently between CMIP5 and CMIP6.  A general code to retrieve these labels from both CMIP5 and CMIP6 files should obtain the name of the variable from the "coordinates" attribute, not assume it will be "passage" or "sector".

**Comment by ledm** [comment]
Thanks @taylor13 & @durack1 , that's very helpful! I think I have been going about this entirely the wrong way. I'll look into what is causing the problems at my end.
